name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Composer audit
        run: composer audit
      - name: Login to github docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sunnybenji
          password: ${{ secrets.TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/sunnybenji/docker_project:1.0.0
